services:
  sandbox:
    build: .
    image: localhost/gemini-sandbox-kali:latest
    pull_policy: never
    container_name: gemini-sandbox-kali
    stdin_open: true
    tty: true
    init: true
    network_mode: "host"
    environment:
      - USER=${USER:-kali}
    volumes:
      - workspace-data:/workspace

volumes:
  workspace-data:
